= User ServerVars II
V 0.1 Marc DEXET (marc.dexet@dsi.cnrs.fr)
Documentation en français
:toc:

== Objet du document
Ce document présente l'application UserServerVars2. Il est rédigé en français et sera traduit en anglais par la suite.

== Présentation
UserSerVars2 est un _fork_ de user_servervars écrit pas *màj*

== Règles de gestion

== Architecture
L'architecture de cette application repose principalement sur les éléments suivants

* un intercepteur
* une liste de jetons
* un backend

== Fonctionnement

L'intercepteur `OCA\User_Servervars2\AppInfo\Interceptor` est déclenché lors que des valeurs du paramètre `?arg=` sont passés dans l'url.

Il en existe deux

* le paramètre d'auto redirection
* le paramètre de vérification

=== paramètre d'auto redirection 

Ce paramètre, dont l'expression est `?arg=usv2redirect`, déclenche la vérification des jetons et, en leur absence, renvoit vers le fournisseur d'identitée (_paramètre de configuration `sso_url`_)

Cet intercepteur va vérifier que les jetons (identifiant, adresse mail, fournisseur d'identité, etc.) sont bien pourvu à l'instant donné.

Il est attendu que _normalement_ lorsque le trigger est déclenché

Le parseur de jetons peut être paramétrés ou une classe dédiée peut être utilisée 

== Autres
