= User ServerVars II
V 0.1 Marc DEXET (marc.dexet@dsi.cnrs.fr)
Documentation en français
:toc:

== Objet du document
Ce document présente l'application UserServerVars2. 
Il est rédigé en français et sera traduit en anglais par la suite.

== Présentation
UserSerVars2 est un _fork_ http://apps.owncloud.com/content/show.php/user_servervars?content=158863[de user_servervars écrit par Jean-Jacques PUIG]

== Architecture
L'architecture de cette application repose principalement sur les éléments suivants

* une liste de jetons
* un intercepteur
* un backend

== Fonctionnement général
Le fonctionnement mets en jeu les acteurs suivants

* L'Utilisateur
* Le Serveur Web
* Le Service OwnCloud
* L'Application UserServervars2
* Le Fournisseur d'Identité


L'Application UserServervars2 peut précéder à l'authentification et l'identification des utilisateurs au vue de certaines variables gérées par le serveur. Généralement ces variables sont valorisées par un mécanisme externe, comme Shibboleth, mod_mellon ou autre. C'est le Fournisseur d'Identitées.footnote:[L'utilisation d'un fournisseur d'identité présuppose la mise en place ou l'utilisation d'outils qui ne seront pas décrites dans le présent document.]

L'Application utilise les informations fournies pour enrichir et mettre à jour le référentiel des utilisateurs de OwnCloud.
 

=== Cas d'usage
Le cas d'usage nominal est le suivant

. l'Utilisateur demande à s'authentifier de OwnCloud via un Fournisseur d'Identité
. OwnCloud renvoie l'Utilisateur vers son Fournisseur d'Identité en utilisant une redirection 
. L'Utilisateur s'authentifie auprès de son Fournisseur d'Identité
. Le Fournisseur d'Identité renvoie l'utilisateur vers OwnCloud avec des informations
. Le Serveur Web enrichit les variables globales ( +$_SERVER+, +$_GET+, etc.)
. l'Application extrait des variables globales les informations pertinentes et en déduit une liste de _jetons_
. l'Application vérifie la validité des jetons
. l'Application déclenche au besoins les actions : 
  * création de l'utilisateur au sens OwnCloud (login, mot de passe, ...) 
  * mise à jour les informations le concernant
  * ajout ou suppression des groupes en fonction des valeurs de jetons
  
== Fonctionnement détaillé des principales classes
=== Jetons
Interface::
 `OCA\User_Servervars2\Service\Tokens`
Responsabilités::
Présenter une vue abstraite des valeurs extraites des informations du fournisseur d'identité
Exemple::
`$uid = $tokens->getUserId();`
Commentaires::
Les jetons sont fournis par une TokensFactory.

[source,php]
----
interface Tokens {

 	/**
 	 * Return the identity provider ( as 'https://idp.example.org/idp/shibboleth')
 	 * @return provider name or false if none
 	 */
 	public function getProviderId();

 	/**
 	 * @return user id or false is none
 	 **/
 	public function getUserId();

 	public function getDisplayName();

 	public function getEmail();

 	/**
 	 * @return array(String => array(String))
	 */
 	public function getGroupsArray();

 }
----

=== Intercepteur
Classe::
`OCA\User_Servervars2\AppInfo\Interceptor`
Responsabilités::
Intercepter les authentifications via un fournisseur d'identité et déclencher les opérations de _provisionning_  
Comportement::
L'intercepteur est déclenché lorsque l'URL contient la requête ('`_query_`')`?app=usv2`.

Exemple _https://my.owncloud.mydomain/index.php?app=usv2_

*Contrairement* à la version d'origine ( `user_servervars` ), *la redirection vers le fournisseur d'identité initial en l'absence de jeton est désactivée*.Elle peut-être réactivée (option <<stop_if_empty>> )

Le parseur de jetons peut être paramétré ou une classe dédiée peut être utilisée (option <<tokens_class>>)

=== Backend
Classe:: 
`OCA\User_Servervars2\Backend\UserBackend`
Responsabilités::
* Répondre de la validité des informations d'authentification de l'utilisateur
* _Décorer_ le véritable backend qui stocke réellement les informations utilisateur. 
Commentaires::
La seule nécessité de ce backend est de fournir la méthode 
[source,php]
public function checkPassword($uid, $password)

== Options de configuration

Les options de configurations sont de 3 natures

. paramètre simple
. classe PHP
. chemin de fichier de configuration de la classe au format json

Elles sont fréparties sur 4 onglets

* A la connexion de l'utilisateur
* URL
* Jetons
* Nommage de groupe


=== URL de redirection vers IDP (Single Sign On Url), 
_clef de configuration: sso_url_

URL de redirection vers le Fournisseur d'identité

=== URL de redirection pour déconnexion (Single Log Out Url), 
_clef de configuration: slo_url_

URL de Single Log Out

=== Libellé du bouton de la page de Login (Login Button Label), 
_clef de configuration: button_name_

Libellé du bouton de la page de Login

=== Créer le compte utilisateur (Auto Create User), 
_clef de configuration:  auto_create_user_

L'option permet de créer des utilisateurs lors de leur première authentification.

=== Mettre à jour informations utilisateur (Update User Data), 
_clef de configuration:  update_user_

Permet de mettre à jour les informations 

=== Arrêter l'authentification si jetons invalides (Stop If Empty), 
_clef de configuration:  stop_if_empty_

L'option _stop_if_empty_ permet d'arrêter le processus enclenché par l'intercepteur si les jetons ne sont pas valides et d'empêcher la redirection automatique vers le fournisseur d'identité.

=== Mettre à jour groupes utilisateur (Update User Groups), 
_clef de configuration:  update_groups_

Mise à jour automatique des groupes. Nécessite l'usage de <<group_naming_class>>

=== Jetons (Tokens), 

La configuration des `Tokens` (`Jetons`) s'effectue à travers les paramètres `token_class` et `tokens_conf` 

==== Classe pour le provisionning utilisateur (Tokens Class), 
_clef de configuration: tokens_class_

Permet de définir une classe héritant de  `OCA\User_Servervars2\Service\Tokens` pour construire des informations à partir des valeurs fournies par le Fournisseur d'Identité

==== Fichier de configuration pour le provisionning utilisateur (Tokens Conf), 
_clef de configuration: tokens_conf_

Permet d'indiquer un fichier de configuration au format json avec son chemin relatif à `apps/user_servervars2` **sans usage des noms de répertoires courant et supérieurs comme `./` et `../`  

==== ConfigurableTokens
La classe `OCA\User_Servervars2\Service\Impl\ConfigurableTokens` peut être configurée à travers des expressions ou des valeurs litterales comme `$_SERVER['mail']` ou `foo@bar` 

Elle doit être configurée à l'aide d'un fichier json mentionné au paramètre `tokens_conf`

Par exemple, la configuration de test custom/foobartokensconfig.json
[source,json]
----
{
	"tokens_provider_id" 	: "provider",
	"tokens_user_id" 		: "foo@bar",
	"tokens_display_name" 	: "Foo BAR",
	"tokens_email" 			: "foo@bar.org",
	"tokens_groups" 		: {
		"ou" : ["FooOU"], "o" : ["barORG"]
	}
}
----

Pour qu'une valeur soit __évaluée_, elle doit être préfixée par `eval:` comme 
`eval:$SERVER['mail']`

WARNING: Il n'est recommandé d'utiliser la classe `ConfigurableTokens` en production, il vaut mieux créer sa propre classe héritant de  `OCA\User_Servervars2\Service\Tokens` et l'adapter à son usage. 

=== Nommage de groupe
La faculté de création de groupe et d'affectation automatiques se font à travers 2 paramètres

==== Classe politique de nommage des groupes (GroupNaming Class), 
_clef de configuration: group_naming_class_

Indique la classe en charge d'appliquer la politique de nommage des groupes.

Cette classe doit implémenter l'interface `OCA\User_Servervars2\Service\GroupNamingService`.

[source,php]
----
namespace OCA\User_Servervars2\Service;
/**
 * Class responsable for group naming
 */
interface GroupNamingService {


	/**
	* For a group array as array('ou' => 'code123'), tells if 'ou' is managed or not.
	* @param String kind
	* @return TRUE if kind is managed by service
	*
	*/
	function isManaged($kind);
	/**
	* @param String value
	* @return boolean validity of group name 
	*/
	function isValid($groupName);

	/**
	* @param String kind of attribute
	* @param String value
	* @return built name according to rules
	**/
	function getName($kind, $value);

}
----

WARNING: La politique de groupe permet d'ajouter mais également de retirer des utilisateurs de groupes. Pour savoir si un groupe est géré ou pas, la classe devra utiliser la méthode `isValid($groupName)`. L'algorithme doit donc être capable de déterminer à partir du simple nom si le groupe est manipulable.
[source,php]
----
	function getOldGroupNames($rawOldGroupIds, $naming) {
        $oldGroupNames = array();
        foreach ($rawOldGroupIds as $value) {
        	if ( $naming->isValid($value)) {
        		$oldGroupNames[] = $value;
        	}
        }
        return $oldGroupNames;
	}
----

==== Fichier de configuration politique de nommage des groupes (GroupNaming Conf), 
_clef de configuration: Group_naming_conf_

Indique l'emplacement du fichier de configuration json attenant.


==== PrependGroupNamingService 

PrependGroupNamingService est une classe qui gère les noms de groupes en ajoutant un suffixe au nom en fonction de ce que la classe _jetons_ retourne à l'appel de la méthode 
[source,php]
public function getGroupsArray();

Un exemple de configuration est 
[source,json]
----
{ "separator": "@", "mapping": { "ou":"unit", "o" :"org" } }
----

Cette configuration fera le lien entre les variables serveur et les noms de groupe. Par exemple si `Tokens::getGroupsArray();` retourne un tableau comme
[source,php]
----
groupsArray = array("ou" => array("paris", "tokyo"), "o" => array("foo", "bar"));
----

Les groupes suivants seront automatiquement mis à jour :

. unit@paris
. unit@tokyo
. org@foo
. org@bar
