= User ServerVars II
V 0.1 Marc DEXET (marc.dexet@dsi.cnrs.fr)
Documentation en français
:toc:

== Objet du document
Ce document présente l'application UserServerVars2. Il est rédigé en français et sera traduit en anglais par la suite.

== Présentation
UserSerVars2 est un _fork_ de user_servervars écrit pas *màj*

== Règles de gestion

== Architecture
L'architecture de cette application repose principalement sur les éléments suivants

* un intercepteur
* une liste de jetons
* un backend

== Fonctionnement

L'intercepteur `OCA\User_Servervars2\AppInfo\Interceptor` est déclenché lorsque l'url contient la requête `?app=usv2`.

Cet intercepteur va vérifier que les jetons (identifiant, adresse mail, fournisseur d'identité, etc.) sont bien pourvu à l'instant donné.

Il est attendu que _normalement_ lorsque le trigger est déclenché quand le jeton est disponible.

*Contrairement* à la version d'origine ( `user_servervars` ), *il n'y a pas de redirection vers le fournisseur d'identité initial*. En effet nous avons estimé que cela représentait un risque important.

Le parseur de jetons peut être paramétrés ou une classe dédiée peut être utilisée 

== Autres
