= User ServerVars II
V 0.1 Marc DEXET (marc.dexet@dsi.cnrs.fr)
Documentation en français
:toc:

== Objet du document
Ce document présente l'application UserServerVars2. Il est rédigé en français et sera traduit en anglais par la suite.

== Présentation
UserSerVars2 est un _fork_ http://apps.owncloud.com/content/show.php/user_servervars?content=158863[de user_servervars écrit par Jean-Jacques PUIG]

== Architecture
L'architecture de cette application repose principalement sur les éléments suivants

* un intercepteur
* une liste de jetons
* un backend

== Fonctionnement général

Cette application délègue l'authentification des utilisateurs à un _fournisseur d'identités_ extérieur à OwnCloud. 
Le scénario de base est celui-ci

. l'Utilisateur demande à s'authentifier de OwnCloud via un fournisseur d'identité
. OwnCloud renvoie l'Utilisateur vers son Fournisseur d'Identité en utilisant une redirection 
. Le Fournisseur d'Identité renvoie l'utilisateur vers OwnCloud avec des informations
. l'Application extrait les informations pertinentes (liste de _jetons_)
.. l'Application vérifie la validité des jetons
.. l'Application peut, au besoin, 
  * créé l'utilisateur
  * mettre à jour les informations le concernant
  * l'ajouter ou le soustraire de groupes en fonction des valeurs de jetons
  
== Fonctionnement détaillé
=== Jetons
Interface::
 `OCA\User_Servervars2\Service\Tokens`
Responsabilités::
Présenter une vue abstraite des valeurs extraites des informations du fournisseur d'identité

=== Intercepteur
Classe::
`OCA\User_Servervars2\AppInfo\Interceptor`
Responsabilité::
Intercepter les authentifications via un fournisseur d'identité et déclencher les opérations de _provisionnoing_  
Comportement::
L'intercepteur est déclenché lorsque l'url contient la requête ('`_query_`')`?app=usv2`.

Exemple _https://my.owncloud.mydomain/index.php?app=usv2_

*Contrairement* à la version d'origine ( `user_servervars` ), *la redirection vers le fournisseur d'identité initial en l'absence de jeton est désactivée*. En effet nous avons estimé que cela représentait un risque important.
Il est attendu que _normalement_ lorsque le trigger est déclenché quand le jeton est disponible.

Le parseur de jetons peut être paramétrés ou une classe dédiée peut être utilisée 

== Autres
